<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c9d4cf01-a128-4c68-96df-e7fee6dbc230</elementGuidId>
    <imagePath></imagePath>
    <name>button_back_to_products</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#back-to-products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'back-to-products') and equals(@name,'back-to-products') and equals(@class,'btn btn_secondary back btn_large inventory_details_back_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary back btn_large inventory_details_back_button</value>
        <webElementGuid>e91237d7-10fe-4235-8636-169bad1f1a73</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>2066be22-df0e-494b-97a5-5a03815a5bbc</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>da06b7c7-d773-4a3a-8a90-e44b8a56e1b3</webElementGuid>
    </webElementProperties>
</WebElementEntity>