<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>571c3ad4-e79e-4e1c-b4c2-00028bb178ba</elementGuidId>
    <imagePath></imagePath>
    <name>button_back_to_products</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/button[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#back-to-products</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'back-to-products') and equals(@name,'back-to-products') and equals(@class,'btn btn_secondary back btn_large inventory_details_back_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_secondary back btn_large inventory_details_back_button</value>
        <webElementGuid>43921eae-8d21-4147-be2e-b21cb6d89727</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>f7417077-009d-467b-9972-94c875d07f86</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>back-to-products</value>
        <webElementGuid>09c2ac2c-e0f3-4892-8cad-b909d832c6fb</webElementGuid>
    </webElementProperties>
</WebElementEntity>