<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>df82d838-7012-4bad-9b69-3b089ef6ab5d</elementGuidId>
    <imagePath></imagePath>
    <name>link_item_0_title_link</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/div[2]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#item_0_title_link</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'item_0_title_link') and equals(@text,'Sauce Labs Bike Light')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="item-0-title-link"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>false</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>item_0_title_link</value>
        <webElementGuid>303ae4b6-30d1-4545-a96b-18ae1cfdd49c</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sauce Labs Bike Light</value>
        <webElementGuid>303ae4b6-30d1-4545-a96b-18ae1cfdd49c</webElementGuid>
    </webElementProperties>
</WebElementEntity>