<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>0c0191ac-a7bb-41c8-8fef-bf96ed68b815</elementGuidId>
    <imagePath></imagePath>
    <name>button_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[9]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#finish</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'finish') and equals(@name,'finish') and equals(@class,'btn btn_action btn_medium cart_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium cart_button</value>
        <webElementGuid>d44fdcbd-fe85-4b59-9ef5-54484dc570a2</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>32104625-5ec2-405f-9271-d05c0d7b253b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>f39f4986-d7a7-4df2-ba01-b32e007ed961</webElementGuid>
    </webElementProperties>
</WebElementEntity>