<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d9117a77-7f5f-4a79-a293-b72ac7d29092</elementGuidId>
    <imagePath></imagePath>
    <name>button_finish</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[1]/div[1]/div[2]/div[1]/div[2]/div[9]/button[2]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>#finish</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'finish') and equals(@name,'finish') and equals(@class,'btn btn_action btn_medium cart_button')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>btn btn_action btn_medium cart_button</value>
        <webElementGuid>55f8bbdb-aa08-46d3-ab81-4d202d41480a</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>8b7eec18-e98d-404b-8db7-8fefea7d7cfb</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>name</name>
        <type>Main</type>
        <value>finish</value>
        <webElementGuid>7149c0ab-a8c4-47d9-a46b-a7f1bc9cc7b8</webElementGuid>
    </webElementProperties>
</WebElementEntity>