<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>495b890b-f883-4416-b512-7e57c60366e0</elementGuidId>
    <imagePath></imagePath>
    <name>input_object_3</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//input[@id='continue']</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>form</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
</WebElementEntity>